version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
      - PORT=3000
    command: >
      sh -c "npx prisma migrate deploy && 
             npx prisma db seed && 
             npm run dev"